# Laboratorio 1 - Introduccion

In [58]:
#import numpy as np
import numpy as np

In [79]:
#lista=[1,2,3]
lista=[1,2,3]
lista2=[[1,1],[2,2],[3,3]]

In [80]:
#lista
lista

[1, 2, 3]

In [61]:
#array=np.array(lista)
array=np.array(lista)

In [62]:
#array
array

array([1, 2, 3])

In [64]:
#lista2=[[1,2,3],[4,5,6],[7,8,9]]
lista2=[[1,2,3],[4,5,6],[7,8,9]]
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [65]:
#array2=np.array(lista2)
array2=np.array(lista2)

In [67]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
#Genera rango de 5 numeros.
#Siempre genera hasta -1 elementos.
#Obj. llenar informacion o validar informacion desde el punto de vista de prediccion.
#array=np.arange(5) 
array=np.arange(6)

In [69]:
array

array([0, 1, 2, 3, 4, 5])

In [71]:
#np.arange(2,10)
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
#np.arange(2,10,2)
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [74]:
#obj.Escalado de imagenes, granuladidad de imagenes.
#En DL para el reconocimiento facial, se necesita implementar zeros.
#np.zeros(3)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [75]:
#np.ones(2)
np.ones(5)

array([1., 1., 1., 1., 1.])

In [83]:
#np.ones((2,5))
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [86]:
#obj. Genera numeros equiespaciados en un rango. 
#np.linspace(5,8,50)
np.linspace(10,40,4)

array([10., 20., 30., 40.])

In [90]:
#obj. crear la matriz identidad.
#Conocer algebra lineal. Matrices, suma, multiplicacion, identidad, inversa.
#Conocer probabilidad y estadistica.
#Conocer calculo 1. Derivadas y integrales. Para el analisis de informacion.
#np.eye(10)
#np.eye(4)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [96]:
#Genera numeros aleatorios
#np.random.rand(5)
#np.random.rand(3)

array([0.57053935, 0.89041177, 0.49593669])

In [102]:
#Crear una matriz 2 filas, 3 columnas
#np.random.rand(2,3)
np.random.rand(3,4)

array([[0.27502191, 0.61611958, 0.95727707, 0.64027349],
       [0.40855939, 0.40852482, 0.50266297, 0.54423426],
       [0.55523806, 0.79043299, 0.53333128, 0.80633389]])

In [108]:
#Crear numeros aleatorios con una distribucion normal.
#DN tratan de tener una distribucion equidistinta para acercarse a la campana de gauss
#np.random.randn(4)
np.random.randn(100)

array([-1.31848761e+00, -9.85745296e-01, -2.39634718e-01, -2.47734398e+00,
        6.63695685e-01, -4.34856467e-01,  1.96772370e-01, -1.27167001e-01,
        1.16572796e+00,  4.38951777e-01, -4.73387205e-01,  1.44548596e+00,
        1.16003730e-01,  3.90419433e-01, -7.56805286e-01,  4.08488090e-01,
       -5.79116686e-01, -4.61364451e-01,  7.73700078e-01, -1.66016225e+00,
        2.26232146e-01,  6.54555986e-01, -5.54948814e-01,  3.58587536e-01,
       -4.90714105e-01,  5.89157993e-01, -1.59910378e+00,  8.25616657e-01,
       -6.26009298e-01,  8.87565868e-01,  5.96449278e-01, -2.02688811e-01,
       -1.06684146e+00,  1.24167814e-01, -1.20227668e+00,  6.37685952e-01,
       -3.96769563e-01,  1.76263291e+00, -5.67619108e-01,  9.32366879e-01,
       -8.47876070e-01, -9.33817014e-01,  2.52361891e-01, -3.46329179e-01,
       -2.28182125e+00,  1.09566202e+00,  9.61046044e-01,  1.23157192e-01,
        2.49728903e+00,  4.80184730e-01, -1.19043568e+00,  5.32392050e-01,
       -6.25754253e-01, -

In [112]:
#Numero aleatorio entre el 1 y 10
#np.random.randint(1,10)
np.random.randint(1,10)

8

In [113]:
#Tres numeros aleatorios entre el 1 y 10
#np.random.randint(1,10,3)
np.random.randint(1,10,2)

array([3, 5])

In [118]:
#array=np.random.randint(1,100,50)
array=np.random.randint(1,100,10)

In [123]:
array

array([71, 85, 81, 89, 59, 15, 27, 78, 14, 63])

In [121]:
#Obtener el valor maximo
#valor_maximo=array.max()
#valor_maximo
valor_maximo=array.max()
valor_maximo

89

In [128]:
#valor_minimo=array.min()
#valor_minimo
valor_minimo=array.min()
valor_minimo

14

In [129]:
#Rango de numero del 0 al 10
#array=np.arange(0,10)
#array
array=np.arange(0,5)
array

array([0, 1, 2, 3, 4])

In [130]:
#array+array
array+array

array([0, 2, 4, 6, 8])

In [131]:
#array-array
array-array

array([0, 0, 0, 0, 0])

In [132]:
#array+5
array+1

array([1, 2, 3, 4, 5])