In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import Imputer

In [3]:
dataset = pd.read_csv("C:/Users/Vic/Documents/CursoMachineLearning/Modulo 1/dataset/data/Data.csv")

In [4]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,3].values

In [6]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [8]:
pd.DataFrame(x)

0    1      2
0   France   44  72000
1    Spain   27  48000
2  Germany   30  54000
3    Spain   38  61000
4  Germany   40    NaN
5   France   35  58000
6    Spain  NaN  52000
7   France   48  79000
8  Germany   50  83000
9   France   37  67000

In [9]:
pd.DataFrame(y)

0
0   No
1  Yes
2   No
3   No
4  Yes
5  Yes
6   No
7  Yes
8   No
9  Yes

In [10]:
imputer = Imputer(missing_values="NaN",strategy="mean", axis=0)

C:\Users\Vic\Anaconda2\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [9]:
imputer = imputer.fit(x[:,1:3])

In [10]:
x[:,1:3] = imputer.transform(x[:,1:3])

In [11]:
pd.DataFrame(x)

0        1        2
0   France       44    72000
1    Spain       27    48000
2  Germany       30    54000
3    Spain       38    61000
4  Germany       40  63777.8
5   France       35    58000
6    Spain  38.7778    52000
7   France       48    79000
8  Germany       50    83000
9   France       37    67000

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
labelencoder_x = LabelEncoder()
labelencoder_x.fit_transform(x[:,0])

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

In [13]:
x[:,0] = labelencoder_x.fit_transform(x[:,0])

In [14]:
pd.DataFrame(x)

0    1      2
0  0   44  72000
1  2   27  48000
2  1   30  54000
3  2   38  61000
4  1   40    NaN
5  0   35  58000
6  2  NaN  52000
7  0   48  79000
8  1   50  83000
9  0   37  67000

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
onehotencoder = OneHotEncoder(categorical_features=[0])

In [17]:
x = onehotencoder.fit_transform(x).toarray()

C:\Users\Vic\Anaconda2\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [19]:
pd.DataFrame(x)

0    1    2          3             4
0  1.0  0.0  0.0  44.000000  72000.000000
1  0.0  0.0  1.0  27.000000  48000.000000
2  0.0  1.0  0.0  30.000000  54000.000000
3  0.0  0.0  1.0  38.000000  61000.000000
4  0.0  1.0  0.0  40.000000  63777.777778
5  1.0  0.0  0.0  35.000000  58000.000000
6  0.0  0.0  1.0  38.777778  52000.000000
7  1.0  0.0  0.0  48.000000  79000.000000
8  0.0  1.0  0.0  50.000000  83000.000000
9  1.0  0.0  0.0  37.000000  67000.000000

In [20]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [21]:
pd.DataFrame(y)

0
0  0
1  1
2  0
3  0
4  1
5  1
6  0
7  1
8  0
9  1

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
sc_x = StandardScaler()

In [26]:
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [27]:
x_train

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [28]:
x_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])